{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "simplyconnect",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.3.0.aar",
          "url": "simplyconnect-1.3.0.aar",
          "size": 239034,
          "sha512": "8a4fa549c439b6ec6cd4b69853341eda26d62a8cf3ed141a3c2d99ccf93692d0729467f76ac89770dbc8c2e4787d9cdfc7e3f01aa9110961e53d26b95d06ac82",
          "sha256": "f9868366c5acb86dee75d1c48247612a4c152072152a697107cea72b2fab74c2",
          "sha1": "2b796fc877e8b0aba67d7f47362f7b2b45666e42",
          "md5": "a6bb5a8e37beeb6275ab25e8b1771152"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.nuvei.mobile.simply-connect-sdk",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.nuvei.mobile.simply-connect-sdk",
          "module": "googlepay",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.3.0.aar",
          "url": "simplyconnect-1.3.0.aar",
          "size": 239034,
          "sha512": "8a4fa549c439b6ec6cd4b69853341eda26d62a8cf3ed141a3c2d99ccf93692d0729467f76ac89770dbc8c2e4787d9cdfc7e3f01aa9110961e53d26b95d06ac82",
          "sha256": "f9868366c5acb86dee75d1c48247612a4c152072152a697107cea72b2fab74c2",
          "sha1": "2b796fc877e8b0aba67d7f47362f7b2b45666e42",
          "md5": "a6bb5a8e37beeb6275ab25e8b1771152"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "simplyconnect-1.3.0-sources.jar",
          "url": "simplyconnect-1.3.0-sources.jar",
          "size": 46275,
          "sha512": "e7c318e5a4a4c256b4e45e906397ae2c12c84d60b75f89cc46360bc5f34636403639ec017da559a96eea85a1b41cfe37db4ac51f405b8605ed0aad54760699eb",
          "sha256": "397edf8ef0068502b62d74c6379b59b3b971c114177c20c0177539bca3ceda5f",
          "sha1": "e4b4fe106048ac744aa0b580e9e4cbc7f3ab835f",
          "md5": "45ad480cb072980acc17f56309d31678"
        }
      ]
    }
  ]
}
