{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "simplyconnect",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.3.0.aar",
          "url": "simplyconnect-1.3.0.aar",
          "size": 240669,
          "sha512": "ee0397016dacee10e2d97665c4f8dfd2feeb853c0c6eda125757c8824cc416d5056332f5f031f389ef56f146643d7e2cb3add89eae8d1cdf1cb7dbe98b67479c",
          "sha256": "d70cbfe8aaa4740ea2d6e2494d3392d2fa4cdc91d9522e76798c4965651e4c66",
          "sha1": "a82d3c35fd942102a1721cce72a4d5edbdfa9d19",
          "md5": "ddc02cc747cd454ca1765bcc831092b7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.nuvei.mobile.simply-connect-sdk",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.nuvei.mobile.simply-connect-sdk",
          "module": "googlepay",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.3.0.aar",
          "url": "simplyconnect-1.3.0.aar",
          "size": 240669,
          "sha512": "ee0397016dacee10e2d97665c4f8dfd2feeb853c0c6eda125757c8824cc416d5056332f5f031f389ef56f146643d7e2cb3add89eae8d1cdf1cb7dbe98b67479c",
          "sha256": "d70cbfe8aaa4740ea2d6e2494d3392d2fa4cdc91d9522e76798c4965651e4c66",
          "sha1": "a82d3c35fd942102a1721cce72a4d5edbdfa9d19",
          "md5": "ddc02cc747cd454ca1765bcc831092b7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "simplyconnect-1.3.0-sources.jar",
          "url": "simplyconnect-1.3.0-sources.jar",
          "size": 46529,
          "sha512": "eeb34494dec6f495bd1879736f862cf631ddebdfc82b45b9a0265abb18881c3c1a7859362ef081e9096c65163ec94e27ac1bb98c58f65c0170a2407b3723e4cf",
          "sha256": "ac6ec42a1952384a6c76db382923b830c9a237586fa0f176dd8a885b0d9ff0bd",
          "sha1": "d077110e101754d7bd4efa2147cdf8de27ac03ad",
          "md5": "2b158dd762c536b3b7f4b4331a979f55"
        }
      ]
    }
  ]
}
