{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "core",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.aar",
          "url": "core-1.3.0.aar",
          "size": 796245,
          "sha512": "f1eedc361c4f01682da45c8932e0df9d370017c52d740c83fdbcebfffb40724d80b79c99ff2b865d4cf8182b3b49e93c3d6664e87e33e09ef34773dc229b6241",
          "sha256": "f15491160e85cf8aba410ad1bbf2da1b955235987495c2a0f220c8dff6aa59b4",
          "sha1": "63e10ff44cf00e6f3957cc2ebf00b1b0003c506d",
          "md5": "c3511237c0fdb570ec9fc9a151c75346"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "org.apache.cxf",
          "module": "cxf-rt-rs-security-jose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "guava-jdk5"
            },
            {
              "group": "com.google.auto.service",
              "module": "auto-service"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.aar",
          "url": "core-1.3.0.aar",
          "size": 796245,
          "sha512": "f1eedc361c4f01682da45c8932e0df9d370017c52d740c83fdbcebfffb40724d80b79c99ff2b865d4cf8182b3b49e93c3d6664e87e33e09ef34773dc229b6241",
          "sha256": "f15491160e85cf8aba410ad1bbf2da1b955235987495c2a0f220c8dff6aa59b4",
          "sha1": "63e10ff44cf00e6f3957cc2ebf00b1b0003c506d",
          "md5": "c3511237c0fdb570ec9fc9a151c75346"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.3.0-sources.jar",
          "url": "core-1.3.0-sources.jar",
          "size": 1042589,
          "sha512": "b5d98deb397cbf0c781cc59fd7538a5da8106a82fd37c19bc6aaf3663b46605f3d7696949a9af2cc5da5bcf7de92a37194073644ef2901ad2964154e5a4d81ea",
          "sha256": "7394a9a29f6860bcd482af10adddffe7a63fd6da8465edbea841ea11e40671e9",
          "sha1": "be91529f204f5861e50f13d07da97c9344512330",
          "md5": "08a97814d9ed7a6e398108bc01803d6a"
        }
      ]
    }
  ]
}
