{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "core",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.aar",
          "url": "core-1.3.0.aar",
          "size": 790655,
          "sha512": "c2908ee45da48279a22521ddeb34365bba15c17473623387fee599f6e3f6e601c03918b91385b3a84861a68a0f8e156555e453ae7ba7ac98a232fb83b13a2835",
          "sha256": "d751fe3c65c28fe31a92fb1336fd12e27bc42883a0344217506813fe7f1b48c9",
          "sha1": "388c8717a90cc81cd77f8cf577e9a0e5a1b47bd3",
          "md5": "14b67a3a48f1ba768c9ce442210acc21"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "org.apache.cxf",
          "module": "cxf-rt-rs-security-jose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "guava-jdk5"
            },
            {
              "group": "com.google.auto.service",
              "module": "auto-service"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.aar",
          "url": "core-1.3.0.aar",
          "size": 790655,
          "sha512": "c2908ee45da48279a22521ddeb34365bba15c17473623387fee599f6e3f6e601c03918b91385b3a84861a68a0f8e156555e453ae7ba7ac98a232fb83b13a2835",
          "sha256": "d751fe3c65c28fe31a92fb1336fd12e27bc42883a0344217506813fe7f1b48c9",
          "sha1": "388c8717a90cc81cd77f8cf577e9a0e5a1b47bd3",
          "md5": "14b67a3a48f1ba768c9ce442210acc21"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.3.0-sources.jar",
          "url": "core-1.3.0-sources.jar",
          "size": 1040683,
          "sha512": "ec04c48d10742c8474d3abec5b68e17ca337463cab37624c339489aa3f85490ce3f37e46581813c2fab7c07442d003da0b8fc34edd2f2f6d81b5cd977f25e4d3",
          "sha256": "95c762697f1746178718198b18f0588d340b17a79cd03e9dac4705eeb97d22e6",
          "sha1": "b51964da4e2fcf6f067f80d16a2ec31672969d98",
          "md5": "82cd391d1df055ff599a8fcd3d4ed446"
        }
      ]
    }
  ]
}
