{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "core",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.aar",
          "url": "core-1.3.0.aar",
          "size": 125462,
          "sha512": "23018dbcbc733671be3a22c07ebcfb7198777aa6bdffcad622792270e9981b1874776e1996146076bc2fdef15a15980c0a8f1416aeed9f1404d544fdbb4681ec",
          "sha256": "62996f0344f80fcc9400dc5c2ba3d90b3525cbc3de1196e1dce33193f6ce4f78",
          "sha1": "d854e8b892c0911dc8e04ce58dcd79b3f92ca6da",
          "md5": "8dcbeda27418cb1b6dd75d87feebc1e8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.aar",
          "url": "core-1.3.0.aar",
          "size": 125462,
          "sha512": "23018dbcbc733671be3a22c07ebcfb7198777aa6bdffcad622792270e9981b1874776e1996146076bc2fdef15a15980c0a8f1416aeed9f1404d544fdbb4681ec",
          "sha256": "62996f0344f80fcc9400dc5c2ba3d90b3525cbc3de1196e1dce33193f6ce4f78",
          "sha1": "d854e8b892c0911dc8e04ce58dcd79b3f92ca6da",
          "md5": "8dcbeda27418cb1b6dd75d87feebc1e8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.3.0-sources.jar",
          "url": "core-1.3.0-sources.jar",
          "size": 45393,
          "sha512": "0df10c4530c186bfc9fffc6984ef1fa3772587747b35b5da90bcdf457dd801687a0c898e80f074d97271cad9b4f20b2e2514f4c89a1d30b3e873c586372ef774",
          "sha256": "4c1b7cde47d2310655e1bcebaaba2db9be761798ea2390e262b1927415809779",
          "sha1": "f2ecab8c1ca94cae42bfc66c7446145234104fd4",
          "md5": "73f817adb88caec7a72bc7516658a179"
        }
      ]
    }
  ]
}
