{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.sdk",
    "module": "core",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.4.4.aar",
          "url": "core-1.4.4.aar",
          "size": 806329,
          "sha512": "b1c6db15c954a79d423c30b092de57aba0ab3b80707da3eb645c768a1e27fa614e68d3121b647bc7bbe411fb08d479b7c6528591d80ea1d1d95905886d686f62",
          "sha256": "5bdb090f283029654e3a0e91aa01938a97288db0249bd2baedaf69f0b29014ce",
          "sha1": "deb93f0e972228acc98374a751aeda74a962326a",
          "md5": "cc23552d624d775e98371c28980df353"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "org.apache.cxf",
          "module": "cxf-rt-rs-security-jose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "guava-jdk5"
            },
            {
              "group": "com.google.auto.service",
              "module": "auto-service"
            }
          ]
        },
        {
          "group": "com.github.stephenc.jcip",
          "module": "jcip-annotations",
          "version": {
            "requires": "1.0-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.4.4.aar",
          "url": "core-1.4.4.aar",
          "size": 806329,
          "sha512": "b1c6db15c954a79d423c30b092de57aba0ab3b80707da3eb645c768a1e27fa614e68d3121b647bc7bbe411fb08d479b7c6528591d80ea1d1d95905886d686f62",
          "sha256": "5bdb090f283029654e3a0e91aa01938a97288db0249bd2baedaf69f0b29014ce",
          "sha1": "deb93f0e972228acc98374a751aeda74a962326a",
          "md5": "cc23552d624d775e98371c28980df353"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.4.4-sources.jar",
          "url": "core-1.4.4-sources.jar",
          "size": 1065513,
          "sha512": "844dd0a513342e8d1dfcd2de957bb7b0a1bc25f7976ef7717b1a02903f631fc933a8954281938474e92c3653e2b66ad90b83d95d9ad73c3e4032b2c3e356f20e",
          "sha256": "b575c494540f6033af3f269dceb5a2b542e7e0f65cac81922ff9fd827d489cdf",
          "sha1": "8325ffe9b10e3ff2d8a61e0d4ec2d52e5db991a1",
          "md5": "3aba89d6ac7ceb8caf03222029df43ad"
        }
      ]
    }
  ]
}
