{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.sdk",
    "module": "core",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.4.3.aar",
          "url": "core-1.4.3.aar",
          "size": 800509,
          "sha512": "14df25c4a27aec84407ff19f3d12a2d0404123a9c80f98e71ad91e831c2903aa2a6d7d4e4e591db1a955f543908f52ebf99698d5dc79047616b89d1a2f9b1b26",
          "sha256": "08b65f69bad41ac9446e5c42980d9c39e184ec9e656a3a4e57f89daea643c2ea",
          "sha1": "da7897d72c0fb0cf74859d97c13273365355dd48",
          "md5": "4823f7cc023d9b6f096f58373b0bf7d5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "org.apache.cxf",
          "module": "cxf-rt-rs-security-jose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "guava-jdk5"
            },
            {
              "group": "com.google.auto.service",
              "module": "auto-service"
            }
          ]
        },
        {
          "group": "com.github.stephenc.jcip",
          "module": "jcip-annotations",
          "version": {
            "requires": "1.0-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.4.3.aar",
          "url": "core-1.4.3.aar",
          "size": 800509,
          "sha512": "14df25c4a27aec84407ff19f3d12a2d0404123a9c80f98e71ad91e831c2903aa2a6d7d4e4e591db1a955f543908f52ebf99698d5dc79047616b89d1a2f9b1b26",
          "sha256": "08b65f69bad41ac9446e5c42980d9c39e184ec9e656a3a4e57f89daea643c2ea",
          "sha1": "da7897d72c0fb0cf74859d97c13273365355dd48",
          "md5": "4823f7cc023d9b6f096f58373b0bf7d5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.4.3-sources.jar",
          "url": "core-1.4.3-sources.jar",
          "size": 1062609,
          "sha512": "5eba4c56bd9816237824b0a4f3db35983d00b106f8f2035a2a774bdb44f93680dedb1ff677315132055fe8b7826b879f5ee2aadea964656cbcf78c258a03dd0b",
          "sha256": "c54d1ae59cf6f72a4d9543716a8f1dc1502e4b7094389571f9558631091cbeb9",
          "sha1": "386a0f29ff2e15cd63ea0999f9decab21780e212",
          "md5": "5b6290635ab4ec6b52345ddc966582fd"
        }
      ]
    }
  ]
}
