{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "googlepay",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.3.0.aar",
          "url": "googlepay-1.3.0.aar",
          "size": 19240,
          "sha512": "f2adc098611a207e484fa30d8528f16f4d51cd4f2416235d62f945f8c69e9ce2692f6e0cfbec3e2e9e5e5d016bc299889a484d77ca932d6ba234975e32c988bb",
          "sha256": "93b41aacdc005274e810102835f57750250247b894264e33d6a54813c272cfac",
          "sha1": "01724627628b7b095257999527c7a47438251f2c",
          "md5": "ca7799ef4addd9a6a0f36d235781c78d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.nuvei.mobile.simply-connect-sdk",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.3.0.aar",
          "url": "googlepay-1.3.0.aar",
          "size": 19240,
          "sha512": "f2adc098611a207e484fa30d8528f16f4d51cd4f2416235d62f945f8c69e9ce2692f6e0cfbec3e2e9e5e5d016bc299889a484d77ca932d6ba234975e32c988bb",
          "sha256": "93b41aacdc005274e810102835f57750250247b894264e33d6a54813c272cfac",
          "sha1": "01724627628b7b095257999527c7a47438251f2c",
          "md5": "ca7799ef4addd9a6a0f36d235781c78d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "googlepay-1.3.0-sources.jar",
          "url": "googlepay-1.3.0-sources.jar",
          "size": 6167,
          "sha512": "1c0b0ae68e92ab3d528c1583fa1d73f9d8b5043788d58b5280bb362765bbc4999928370099c231f6706640bd97f4ca0267cfda2c271a2aa42921546567f224c4",
          "sha256": "fbd74325b313197df4441aca5042b807e723ec2a0beb1af038d542e95278d328",
          "sha1": "8a75b72d3498273ee77080af97d8cab1a2286c57",
          "md5": "f3bd73d0847d63b146f38353aefa981e"
        }
      ]
    }
  ]
}
