{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "googlepay",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.3.0.aar",
          "url": "googlepay-1.3.0.aar",
          "size": 19247,
          "sha512": "70e48a044629d239b091b3672794757bf549c16f08c7bf2141aa219e0ea0e757982c99f30f8aa800e78e1e5d14c6afe6061460d7d9c03536df9686bb72a7da67",
          "sha256": "02ae54521ce4997148d7f7a2e488919b682d2ce1c0868c449c2dedd74c793157",
          "sha1": "4e4796a925e66c62bf12f0a37ba3300a8c82be3e",
          "md5": "95b8c4294ec2c399c0a4c6a1167b8e5a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.nuvei.mobile.simply-connect-sdk",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.3.0.aar",
          "url": "googlepay-1.3.0.aar",
          "size": 19247,
          "sha512": "70e48a044629d239b091b3672794757bf549c16f08c7bf2141aa219e0ea0e757982c99f30f8aa800e78e1e5d14c6afe6061460d7d9c03536df9686bb72a7da67",
          "sha256": "02ae54521ce4997148d7f7a2e488919b682d2ce1c0868c449c2dedd74c793157",
          "sha1": "4e4796a925e66c62bf12f0a37ba3300a8c82be3e",
          "md5": "95b8c4294ec2c399c0a4c6a1167b8e5a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "googlepay-1.3.0-sources.jar",
          "url": "googlepay-1.3.0-sources.jar",
          "size": 6167,
          "sha512": "1c0b0ae68e92ab3d528c1583fa1d73f9d8b5043788d58b5280bb362765bbc4999928370099c231f6706640bd97f4ca0267cfda2c271a2aa42921546567f224c4",
          "sha256": "fbd74325b313197df4441aca5042b807e723ec2a0beb1af038d542e95278d328",
          "sha1": "8a75b72d3498273ee77080af97d8cab1a2286c57",
          "md5": "f3bd73d0847d63b146f38353aefa981e"
        }
      ]
    }
  ]
}
