{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile",
    "module": "googlepay",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.3.0.aar",
          "url": "googlepay-1.3.0.aar",
          "size": 17649,
          "sha512": "91672828ea6b7c338503cee41972096aa8c26490ce08f2df442228d57ac61084d9deb48edfcb7774e6c21d84de79e7e353d16bf12566dac8e3cfab25553519ca",
          "sha256": "c1c0559f6c1e46ebb0a09d75b2f5f6904cec9fa955aa37cd1a8cc22a9b339cb0",
          "sha1": "aba4d892d26ef213b97a1546ab86c39848610e59",
          "md5": "35145fa8b2c14b2f57c8a84f03e1b965"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "Nuvei Mobile SDK",
          "module": "Core",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.3.0.aar",
          "url": "googlepay-1.3.0.aar",
          "size": 17649,
          "sha512": "91672828ea6b7c338503cee41972096aa8c26490ce08f2df442228d57ac61084d9deb48edfcb7774e6c21d84de79e7e353d16bf12566dac8e3cfab25553519ca",
          "sha256": "c1c0559f6c1e46ebb0a09d75b2f5f6904cec9fa955aa37cd1a8cc22a9b339cb0",
          "sha1": "aba4d892d26ef213b97a1546ab86c39848610e59",
          "md5": "35145fa8b2c14b2f57c8a84f03e1b965"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "googlepay-1.3.0-sources.jar",
          "url": "googlepay-1.3.0-sources.jar",
          "size": 5811,
          "sha512": "15370a48d13560501fcd08f762bc6e328be56d44bb953bc1d818c2dcdce01b9c495ad11e7f661e85fc4516896139dd0cbe0c0ff4869a7d37aa2fcf97b8fc6095",
          "sha256": "30f57bde77f92d0f689405f5e545afea56b77565d5173512f59b10438a05f407",
          "sha1": "6f861946dd5599cd3ad84425b86373ecf5830557",
          "md5": "30ed96d89944f5b207c526cffb7af7a8"
        }
      ]
    }
  ]
}
