{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.simply-connect-sdk",
    "module": "fields",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fields-1.3.0.aar",
          "url": "fields-1.3.0.aar",
          "size": 70623,
          "sha512": "009afa841e1a6484632280654da875344defc62e9463480b371d2df07f04ea6290faa76b24151558ee35f86f73cbf1f992cb662b662b33cad1946482b6215c4f",
          "sha256": "23ad6dd249672dcb59b1650bbf73c04561ac78ef189bea8de46f53ebaacf5370",
          "sha1": "3d2a102334218ee0e6a6a74317a462ca64e3a3cf",
          "md5": "e3882fd6d7b266a78545120e4002771d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.nuvei.mobile.simply-connect-sdk",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "fields-1.3.0.aar",
          "url": "fields-1.3.0.aar",
          "size": 70623,
          "sha512": "009afa841e1a6484632280654da875344defc62e9463480b371d2df07f04ea6290faa76b24151558ee35f86f73cbf1f992cb662b662b33cad1946482b6215c4f",
          "sha256": "23ad6dd249672dcb59b1650bbf73c04561ac78ef189bea8de46f53ebaacf5370",
          "sha1": "3d2a102334218ee0e6a6a74317a462ca64e3a3cf",
          "md5": "e3882fd6d7b266a78545120e4002771d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fields-1.3.0-sources.jar",
          "url": "fields-1.3.0-sources.jar",
          "size": 19169,
          "sha512": "f14b51a95e149d6ef364a233c365ae27a4a17b10ebdd8b5d7ed6bed12154555c37e783e8a39c0f72a0d50e049051687acd2f9e5b5e01f166f247e04238a28167",
          "sha256": "4059e94224f72bb8e414abc9ddca521987f5da56ab7ddb5a92f02c5de6d48f6b",
          "sha1": "36e20bd75314dc6286f5ada69fa51ee980dd1549",
          "md5": "b4d1ad05e56a6bc3cdb8ad6638d6990a"
        }
      ]
    }
  ]
}
