{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.sdk",
    "module": "simplyconnect",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.4.4.aar",
          "url": "simplyconnect-1.4.4.aar",
          "size": 311013,
          "sha512": "cc821d1e915ce1e3171adb3d61cb5366261a2d026fdba23ca33ede681e2050911d125771706cbddbf1e6b020fa498de8102c6fd933ef4b2bb6bb82e3a92d3810",
          "sha256": "e48f6d75c445879108b4bf166d1d700c60531dca719397a183488cfb568c18f0",
          "sha1": "0a21742b8990463e6f64cf0f1cbcf5d9de8ae7e3",
          "md5": "97d4116a33fb96b9516d45226d239bb6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.nuvei.mobile.sdk",
          "module": "core",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "com.nuvei.mobile.sdk",
          "module": "googlepay",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.4.4.aar",
          "url": "simplyconnect-1.4.4.aar",
          "size": 311013,
          "sha512": "cc821d1e915ce1e3171adb3d61cb5366261a2d026fdba23ca33ede681e2050911d125771706cbddbf1e6b020fa498de8102c6fd933ef4b2bb6bb82e3a92d3810",
          "sha256": "e48f6d75c445879108b4bf166d1d700c60531dca719397a183488cfb568c18f0",
          "sha1": "0a21742b8990463e6f64cf0f1cbcf5d9de8ae7e3",
          "md5": "97d4116a33fb96b9516d45226d239bb6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "simplyconnect-1.4.4-sources.jar",
          "url": "simplyconnect-1.4.4-sources.jar",
          "size": 76245,
          "sha512": "c64b21455aafb62980034a32c10f15a0105fc8a893a93a9774beea3bc7ba6c4eab5e61475a9caca7ca2fba0f37b4676cd7cc1ec2b4575e1c042c94e17655f03c",
          "sha256": "80d4b2b402fb56a237d4a740077e2db0282a6e562998d6eb41b4e7124ce124b3",
          "sha1": "1510ab87b68ea44d0a2cc366a13c2dbdd3345a95",
          "md5": "940e0abd59a6a0fbe50d256377564ad1"
        }
      ]
    }
  ]
}
