{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.sdk",
    "module": "simplyconnect",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.4.4.aar",
          "url": "simplyconnect-1.4.4.aar",
          "size": 307968,
          "sha512": "7e85e3a578bf13429825002e18ace13560b82be0a3d97c9c75bf0f8cd96bae3457438215311097c6c06b136ef10b9ac747b76feff4bf20c8cddad292f9ec2da1",
          "sha256": "a9c261c6dec6baf89fa93eceaafb64089e4c97e5f7c6fb214609bea28edd27d6",
          "sha1": "fc5d8eb198d30bab4d063686135d229732354d64",
          "md5": "4cd6456f990852a3eb289c0c6f828b27"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.nuvei.mobile.sdk",
          "module": "core",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "com.nuvei.mobile.sdk",
          "module": "googlepay",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "simplyconnect-1.4.4.aar",
          "url": "simplyconnect-1.4.4.aar",
          "size": 307968,
          "sha512": "7e85e3a578bf13429825002e18ace13560b82be0a3d97c9c75bf0f8cd96bae3457438215311097c6c06b136ef10b9ac747b76feff4bf20c8cddad292f9ec2da1",
          "sha256": "a9c261c6dec6baf89fa93eceaafb64089e4c97e5f7c6fb214609bea28edd27d6",
          "sha1": "fc5d8eb198d30bab4d063686135d229732354d64",
          "md5": "4cd6456f990852a3eb289c0c6f828b27"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "simplyconnect-1.4.4-sources.jar",
          "url": "simplyconnect-1.4.4-sources.jar",
          "size": 75891,
          "sha512": "f178f9817af2417355d1bd198ad05afeef1d2b86f482ac9c451a2a7d9102718490671f9c087aef489319d0c65d364105aaa18264630c4982ecbf45e77020dfaa",
          "sha256": "2938f553b3d41ba0a3f7538cb9303f28a840955be8ca3636e39c668f5acebbfe",
          "sha1": "83cc7d814dfb482ae75e1f5ff46376ed1663cdf0",
          "md5": "47ce7e7946b2c62cd66bd1c986600553"
        }
      ]
    }
  ]
}
