{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.sdk",
    "module": "googlepay",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.4.0.aar",
          "url": "googlepay-1.4.0.aar",
          "size": 19472,
          "sha512": "5ca56638de95f85f6465f682bcd0ba8e2cfceabff48458085ab759cfd7c0da6c5532ed88a4855d1b033d1184cdcb1d36bb3b0b0914bd5411598f49a499298d2a",
          "sha256": "5593a52873b9e3b140c89897dab87be90120c3346e4d14f0d68f86c1da28171d",
          "sha1": "de59f402d766eeb3bfd6b80048dbabc2860e7c71",
          "md5": "1b7f04d363c62b16dd6f6895f4a191f2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "com.nuvei.mobile.sdk",
          "module": "core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "googlepay-1.4.0.aar",
          "url": "googlepay-1.4.0.aar",
          "size": 19472,
          "sha512": "5ca56638de95f85f6465f682bcd0ba8e2cfceabff48458085ab759cfd7c0da6c5532ed88a4855d1b033d1184cdcb1d36bb3b0b0914bd5411598f49a499298d2a",
          "sha256": "5593a52873b9e3b140c89897dab87be90120c3346e4d14f0d68f86c1da28171d",
          "sha1": "de59f402d766eeb3bfd6b80048dbabc2860e7c71",
          "md5": "1b7f04d363c62b16dd6f6895f4a191f2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "googlepay-1.4.0-sources.jar",
          "url": "googlepay-1.4.0-sources.jar",
          "size": 6255,
          "sha512": "1bafb6743936a432024fb8437aaa4138c356e4d9c526a366cac02629106c5e961f44928e3fe62c043f0bbc0425307e84077feb57d841246165c8e251bbd444af",
          "sha256": "724a4555bd000d391632fd0aec591276a469315d0923f174a40225e663dae705",
          "sha1": "0aedc648dfbdfa596a6381664373fb38942ce453",
          "md5": "592524465cbe2673dea508462b9494bc"
        }
      ]
    }
  ]
}
