{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nuvei.mobile.sdk",
    "module": "core",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.4.5.aar",
          "url": "core-1.4.5.aar",
          "size": 797693,
          "sha512": "92eec8c34e39068c05a48dda36eedfdc246acc6a6116264d64f47a3885258fb2b09670c23678e9f71846d0821000df2188f16505127d4946d6665ef2c4f9df43",
          "sha256": "ef385d16f7dc514822527c6546b08e97565efe471b97f8f0185b1fecc93abeaf",
          "sha1": "d3b93ea3ec2478f258f29a7ca5da10962882a14c",
          "md5": "d0f0da15755a487be0a535da97ba3225"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "org.apache.cxf",
          "module": "cxf-rt-rs-security-jose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "guava-jdk5"
            },
            {
              "group": "com.google.auto.service",
              "module": "auto-service"
            }
          ]
        },
        {
          "group": "com.github.stephenc.jcip",
          "module": "jcip-annotations",
          "version": {
            "requires": "1.0-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.4.5.aar",
          "url": "core-1.4.5.aar",
          "size": 797693,
          "sha512": "92eec8c34e39068c05a48dda36eedfdc246acc6a6116264d64f47a3885258fb2b09670c23678e9f71846d0821000df2188f16505127d4946d6665ef2c4f9df43",
          "sha256": "ef385d16f7dc514822527c6546b08e97565efe471b97f8f0185b1fecc93abeaf",
          "sha1": "d3b93ea3ec2478f258f29a7ca5da10962882a14c",
          "md5": "d0f0da15755a487be0a535da97ba3225"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.4.5-sources.jar",
          "url": "core-1.4.5-sources.jar",
          "size": 1055385,
          "sha512": "93edc1c05935b34fae48ef48663e0feed27a79b8cf6e7c99e669b392ccb5f6341875d8bd6921eb70b56bc9df083748e6000b7ecc150a0e4119c6164ee172da83",
          "sha256": "ba994c263f44d47b58d05dee0f218b44f183cffd0f065ed8e9092bbf59b92200",
          "sha1": "9b27cd3dfd0d22904971f0a44ca8bf85613e947d",
          "md5": "cff978f5b0452b7d3b655aa025dae69c"
        }
      ]
    }
  ]
}
